### ISSUE TITLE
had to specifically include in application.html.haml

### ISSUE THREAD

**Issue by dchersey** [iblue/d3-rails#34]
I included this gem, but was unable to get the asset pipeline to pick it up with 
#= require d3 in application.js.coffee

I wound up including the script directly in application.html.haml
= javascript_include_tag 'd3.min.js'

I'm using Rails 4.2.1 and ruby 2.2.2

Any ideas why?

**Comment by iblue** [comment]
Not really. Did you manage to solve the problem in the mean time?
