### ISSUE TITLE
Cannot update d3 version

### ISSUE THREAD

**Issue by ian-s-mcb** [iblue/d3-rails#35]
I'm using d3-rails 3.5.6, ruby 2.2.0, rvm 1.26.11

Error message:
```bash
$ bundle exec rake d3:update_version
rake aborted!
Don't know how to build task 'd3:update_version'

(See full trace by running task with --trace)
```

**Comment by ian-s-mcb** [comment]
The Rakefile in my d3-rails Gem folder doesn't match what's in https://github.com/iblue/d3-rails/blob/master/Rakefile

The Rakefile in questions contains only two lines:
```
require 'bundler'
Bundler::GemHelper.install_tasks
```

**Comment by iblue** [comment]
You cannot use it to update the version in your application (see my comment in #32). In the new release (3.5.11), the `update_version` task is included in the gem.
